- name: a git checkout that runs on local host
  local_action: git repo=git@github.com:ZanichelliEditore/sendy.git dest=src version={{ checkout_branch }} accept_hostkey=yes
  become: false
  notify: Remove local checkout
