---
- name: Create base deploy path folder
  become: true
  ansible.builtin.file:
    path: "{{ deploy_path }}"
    state: directory
    group: "{{ remote_user }}"
    owner: "{{ remote_user }}"

- name: Create certs folder
  become: true
  ansible.builtin.file:
    path: "{{ deploy_path }}/certs"
    state: directory
    group: "{{ remote_user }}"
    owner: "{{ remote_user }}"

- name: Synchronize files to Zanichelli application folder
  synchronize:
    src: src/
    dest: "{{ deploy_path }}"
    checksum: yes
    archive: no
    delete: no
    recursive: yes
    use_ssh_args: yes
    rsync_opts:
      - "-v"
      - "--exclude=*.git"
      - "--exclude=.git*"
      - "--include=*"

- name: Copy across new env file for the laravel app
  template: src=.env.j2
    dest={{ deploy_path }}/.env

- name: Copy across new cert file 1
  template: src=star_certificate.crt
    dest={{ deploy_path }}/certs/star_certificate.crt

- name: Copy across new cert file 2
  template: src=star_certificate.key
    dest={{ deploy_path }}/certs/star_certificate.key

- name: Copy across oauth_public.key
  template: src=oauth-public.key
    dest={{ deploy_path }}/storage/oauth-public.key

- name: Copy across oauth_private.key
  template: src=oauth-private.key
    dest={{ deploy_path }}/storage/oauth-private.key

- name: Adding existing user 'root' to group docker
  become: true
  user:
    name: "{{ remote_user }}"
    groups: docker
    append: yes

- name: reset connection for user ubuntu
  meta: reset_connection

- name: Remove the containers
  command: "/usr/local/bin/docker-compose -f {{ deploy_path }}/docker-compose.prod.yml down"
  ignore_errors: true
  args:
    chdir: "{{ deploy_path }}"

- name: Start and build the containers
  command: "/usr/local/bin/docker-compose -f {{ deploy_path }}/docker-compose.prod.yml up -d --build"
  args:
    chdir: "{{ deploy_path }}"

- name: Install npm
  command: "/usr/local/bin/docker-compose -f {{ deploy_path }}/docker-compose.prod.yml run --rm nodejs npm install"
  args:
    chdir: "{{ deploy_path }}"

- name: Run npm
  command: "/usr/local/bin/docker-compose -f {{ deploy_path }}/docker-compose.prod.yml run --rm nodejs npm run prod"
  args:
    chdir: "{{ deploy_path }}"

- name: Run composer install
  command: "/usr/bin/docker exec sendy_app composer install"

- name: Run migrations
  command: "/usr/bin/docker exec sendy_app php artisan migrate --force"

- name: Run generate documentation
  command: "docker exec sendy_app php artisan l5-swagger:generate"

- name: Copy public files into nginx container
  command: "docker cp sendy_app:/var/www/public/. ./public/"
  become: true
  args:
    chdir: "{{ deploy_path }}"

- name: Copy public folder into sendy_web public folder
  command: "docker cp ./public/. sendy_web:/var/www/public/"
  args:
    chdir: "{{ deploy_path }}"

- name: Copy public files into sendy_app container
  command: "docker cp ./public/. sendy_app:/var/www/public/"
  args:
    chdir: "{{ deploy_path }}"

- name: Reload builded files
  command: "/usr/local/bin/docker-compose -f {{ deploy_path }}/docker-compose.prod.yml up -d --build"
  args:
    chdir: "{{ deploy_path }}"

- name: Create crontab job to run laravel scheduler
  ansible.builtin.cron:
    name: "Run laravel scheduler"
    job: "/usr/bin/docker exec {{ app_docker }} php artisan schedule:run"
