version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "master"  
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "composer"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "composer"
      - "dependencies"