version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "SND-14"  
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"

  - package-ecosystem: "composer"
    target-branch: "SND-14"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "composer"
      - "dependencies"