services:
  web:
    build:
      context: ./
      dockerfile: web-prod.dockerfile
    container_name: sendy_web
    ports:
      - "443:443"
    links:
      - app
    restart: unless-stopped
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"
  app:
    build:
      context: ./
      dockerfile: app-prod.dockerfile
    container_name: sendy_app
    restart: unless-stopped
    volumes:
      - appStorage:/var/www/storage
      - appVendor:/var/www/vendor
      - appLogs:/var/www/storage/logs
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"
  nodejs:
    image: node:23-alpine
    container_name: sendy_nodejs
    volumes:
      - ./:/var/www/
    working_dir: /var/www
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"
  filebeat:
    build:
      context: ./
      dockerfile: filebeat.dockerfile
    container_name: sendy_filebeat
    environment:
      - strict.perms=false
      - "LOGSTASH_HOST=${LOGSTASH_HOST}"
    volumes:
      - appLogs:/app/log/
    restart: always
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"
volumes:
  appStorage:
  appVendor:
  appLogs:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
