version: "2"
services:
  web:
    build:
      context: ./
      dockerfile: web-prod.dockerfile
    container_name: sendy_web
    volumes:
      - app:/var/www
    ports:
      - "8743:443"
    links:
      - app
    restart: always
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"
  app:
    build:
      context: ./
      dockerfile: app-prod.dockerfile
    container_name: sendy_app
    volumes:
      - app:/var/www
      - appStorage:/var/www/storage
      - appVendor:/var/www/vendor
      - appNode:/var/www/node_modules
    environment:
      - "DB_HOST=mongodb"
      - "DB_PORT=27017"
    restart: always
    networks:
      - default
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"
  mongodb:
    image: mongo:latest
    container_name: sendy_mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - appMongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"
  nodejs:
    build:
      context: images/node
    container_name: sendy_nodejs
    volumes:
      - app:/var/www/
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"
volumes:
  app:
  appStorage:
  appVendor:
  appMongo:
  appNode:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
