version: "3"
services:
  web:
    container_name: sendy_web
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8083:80"
    links:
      - app
    networks:
      - default
  app:
    container_name: sendy_app
    build:
      context: ./
      dockerfile: app-dev.dockerfile
      args:
        - USER=${USER}
        - UID=${UID}
    volumes:
      - ./:/var/www
      - ./custom.d:/usr/local/etc/php/custom.d
    environment:
      - "PHP_INI_SCAN_DIR=/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
      - "REDIS_HOST=redis"
    links:
      - database
      - redis
    depends_on:
      - database
    networks:
      - default
  nodejs:
    image: node:23-alpine
    container_name: sendy_nodejs
    volumes:
      - ./:/var/www/
    working_dir: /var/www
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"

  database:
    image: mysql:5.7
    container_name: sendy_db
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
    ports:
      - "33064:3306"
    networks:
      - default
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: sendy_phpmyadmin
    links:
      - database
    ports:
      - "8084:80"
    environment:
      - "PMA_HOST=${DB_HOST}"
      - "PMA_USER=${DB_USERNAME}"
      - "PMA_PASSWORD=${DB_PASSWORD}"
    networks:
      - default
  redis:
    container_name: sendy_redis
    image: redis:5.0.5
    ports:
      - "6380:6379"
    networks:
      - default
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
