---
- name: Revert to older image
  command: "/usr/bin/docker tag sendy_app:previous sendy_app:latest"

- name: Recreate containers using older image
  command: "/usr/local/bin/docker-compose -f {{ deploy_path }}/docker-compose.prod.yml up -d"
  args:
    chdir: "{{ deploy_path }}"

- name: Install npm
  command: "/usr/local/bin/docker-compose -f {{ deploy_path }}/docker-compose.prod.yml run --rm nodejs npm install"
  args:
    chdir: "{{ deploy_path }}"

- name: Run npm
  command: "/usr/local/bin/docker-compose -f {{ deploy_path }}/docker-compose.prod.yml run --rm nodejs npm run prod"
  args:
    chdir: "{{ deploy_path }}"

- name: Run composer install
  command: "/usr/bin/docker exec sendy_app composer install"
