---
- hosts: sendy
  remote_user: "{{ remote_user }}"
  vars_files:
    - vars/sendy.yml
  roles:
    - { role: deploy-sendy, tags: ["deploy-sendy"] }

- hosts: sendy
  remote_user: "{{ remote_user }}"
  vars_files:
    - vars/sendy.yml
  roles:
    - { role: revert-sendy, tags: ["revert-deploy"] }
